import { useEffect, useMemo, useRef, useState } from 'react';
import type { ArtistNode } from '../api/apiTypes';
import type { GraphPhase } from '../types';
import { ACTIVE_BUBBLE_RADIUS, DRIFT_STRENGTH, EXPLOSION_SPEED, FLY_IN_SPEED, IDLE_DAMPING } from '../utils/animationConstants';
import { pickOffscreen } from '../utils/graphLayout';

type SimNode = ArtistNode & { x:number;y:number;vx:number;vy:number;tx:number;ty:number;r:number;opacity:number;scale:number;selected?:boolean };
const textRadius = (name: string) => Math.max(28, name.length * 3.8 + 14);

export function BubbleGraph({ activeArtist, similarArtists, onSelectArtist, phase, setPhase }: { activeArtist: ArtistNode; similarArtists: ArtistNode[]; onSelectArtist: (a: ArtistNode) => boolean; phase: GraphPhase; setPhase: (p: GraphPhase) => void }) {
 const wrap=useRef<HTMLDivElement>(null); const [size,setSize]=useState({w:900,h:620}); const [tick,setTick]=useState(0); const center=useMemo(()=>({x:size.w/2,y:size.h/2}),[size]); const nodes=useRef<SimNode[]>([]); const activeScale=useRef(1); const activeLabel=useRef(activeArtist.name); const activePos=useRef({x:center.x,y:center.y,vx:0,vy:0,exploding:false}); const pending=useRef<SimNode|null>(null);
 const placeTargets=(list:SimNode[])=>{const circumference=list.reduce((s,n)=>s+n.r*2+14,0); const ring=Math.max(ACTIVE_BUBBLE_RADIUS+30+Math.max(...list.map((n)=>n.r),1),circumference/(2*Math.PI)); let arc=-Math.PI/2; for(const n of list){const w=(n.r*2+14)/ring; arc+=w/2; n.tx=center.x+Math.cos(arc)*ring; n.ty=center.y+Math.sin(arc)*ring; arc+=w/2;}};
 const initNodes=()=>{const list:SimNode[]=similarArtists.map((n)=>({...n,r:textRadius(n.name)+(n.similarity??0.6)*8,x:0,y:0,vx:0,vy:0,tx:0,ty:0,opacity:0,scale:1})); placeTargets(list); nodes.current=list.map((n)=>({...n,...pickOffscreen(size.w,size.h)}));};
 useEffect(()=>{const ro=new ResizeObserver(()=>{const r=wrap.current?.getBoundingClientRect(); if(r)setSize({w:r.width,h:r.height});}); if(wrap.current)ro.observe(wrap.current); return ()=>ro.disconnect();},[]);
 useEffect(()=>{activeLabel.current=activeArtist.name; activePos.current={x:center.x,y:center.y,vx:0,vy:0,exploding:false}; initNodes(); setPhase('fly-in-new-neighbours');},[activeArtist.id,activeArtist.name,similarArtists,center.x,center.y]);
 useEffect(()=>{let raf=0; const frame=()=>{if(phase==='fly-in-new-neighbours'){let done=true; for(const n of nodes.current){const dx=n.tx-n.x; const dy=n.ty-n.y; n.x+=dx*FLY_IN_SPEED; n.y+=dy*FLY_IN_SPEED; n.opacity=Math.min(1,n.opacity+0.04); if(Math.hypot(dx,dy)>3)done=false;} if(done){setPhase('collision-pulse'); activeScale.current=0.92; setTimeout(()=>activeScale.current=1.05,120); setTimeout(()=>{activeScale.current=1; setPhase('settle');},300);}} else if(phase==='explode-out'){let out=true; if(activePos.current.exploding){activePos.current.x+=activePos.current.vx; activePos.current.y+=activePos.current.vy;} for(const n of nodes.current){if(n.selected){n.x+=(center.x-n.x)*0.06; n.y+=(center.y-n.y)*0.06; continue;} const dx=n.x-center.x; const dy=n.y-center.y; const mag=Math.max(0.01,Math.hypot(dx,dy)); n.x+=(dx/mag)*EXPLOSION_SPEED; n.y+=(dy/mag)*EXPLOSION_SPEED; n.opacity=Math.max(0,n.opacity-0.03); if(n.x>-220&&n.x<size.w+220&&n.y>-220&&n.y<size.h+220) out=false;} if(pending.current&&Math.hypot(center.x-pending.current.x,center.y-pending.current.y)<6){const selected=pending.current; pending.current=null; onSelectArtist(selected);} if(out&&pending.current===null)setPhase('recenter-new-active');} else if(phase==='idle'||phase==='settle'){for(let i=0;i<nodes.current.length;i++){const n=nodes.current[i]; const dx=n.tx-n.x; const dy=n.ty-n.y; n.vx=(n.vx+dx*0.02+(Math.random()-0.5)*DRIFT_STRENGTH)*IDLE_DAMPING; n.vy=(n.vy+dy*0.02+(Math.random()-0.5)*DRIFT_STRENGTH)*IDLE_DAMPING; n.x+=n.vx; n.y+=n.vy;} if(phase==='settle')setPhase('idle');} setTick((t)=>(t+1)%100000); raf=requestAnimationFrame(frame);}; raf=requestAnimationFrame(frame); return ()=>cancelAnimationFrame(raf);},[phase,center.x,center.y,onSelectArtist,setPhase,size.h,size.w,activeArtist.name]);
 const select=(n:SimNode)=>{if(phase!=='idle')return; pending.current=n; for(const node of nodes.current) node.selected=node.id===n.id; n.scale=1.16; activeLabel.current=activeArtist.name; const angle=Math.atan2(center.y-n.y,center.x-n.x)+Math.PI; activePos.current={x:center.x,y:center.y,vx:Math.cos(angle)*EXPLOSION_SPEED,vy:Math.sin(angle)*EXPLOSION_SPEED,exploding:true}; setPhase('inflate-selected'); setTimeout(()=>setPhase('explode-out'),200);};
 return <div className="graph" ref={wrap}><svg viewBox={`0 0 ${size.w} ${size.h}`} data-tick={tick}><g transform={`translate(${activePos.current.x},${activePos.current.y}) scale(${activeScale.current})`} style={{ opacity: activePos.current.exploding ? 0.9 : 1 }}><circle r={ACTIVE_BUBBLE_RADIUS} className="activeBubble" /><text textAnchor="middle" y="4" className="label">{activeLabel.current}</text></g>{nodes.current.map((n)=><g key={n.id} transform={`translate(${n.x},${n.y}) scale(${n.scale})`} onClick={()=>select(n)} style={{ opacity: n.selected ? 1 : n.opacity, cursor: 'pointer' }}><circle r={n.r + 8} fill="transparent" /><circle r={n.r} className={n.selected && phase !== 'idle' ? 'activeBubble' : 'relatedBubble'} /><text textAnchor="middle" y="4" className="label">{n.name}</text></g>)}</svg></div>;
}
