import type { ArtistNeighbourhood, MockPlayer } from './types';

const A = (id: string, name: string, similarity: number) => ({ id, name, similarity });

export const neighbourhoods: Record<string, ArtistNeighbourhood> = {
  radiohead: {
    artist: { id: 'radiohead', name: 'Radiohead' },
    similarArtists: [A('the-smile', 'The Smile', 0.95), A('thom-yorke', 'Thom Yorke', 0.9), A('muse', 'Muse', 0.83), A('pink-floyd', 'Pink Floyd', 0.81), A('massive-attack', 'Massive Attack', 0.79), A('portishead', 'Portishead', 0.78), A('bjork', 'Björk', 0.77), A('aphex-twin', 'Aphex Twin', 0.72), A('the-cure', 'The Cure', 0.71), A('depeche-mode', 'Depeche Mode', 0.69), A('arcade-fire', 'Arcade Fire', 0.66), A('lcd-soundsystem', 'LCD Soundsystem', 0.64), A('david-bowie', 'David Bowie', 0.63), A('talking-heads', 'Talking Heads', 0.6)],
    albums: [{ id: 'okc', title: 'OK Computer', artistId: 'radiohead', artistName: 'Radiohead', year: 1997, popularity: 98 }, { id: 'kid-a', title: 'Kid A', artistId: 'radiohead', artistName: 'Radiohead', year: 2000, popularity: 96 }],
    tracks: [{ id: 'eiirp', title: 'Everything In Its Right Place', artistId: 'radiohead', artistName: 'Radiohead', popularity: 95 }, { id: 'idioteque', title: 'Idioteque', artistId: 'radiohead', artistName: 'Radiohead', popularity: 93 }]
  },
  'the-smile': { artist: { id: 'the-smile', name: 'The Smile' }, similarArtists: [A('radiohead', 'Radiohead', 0.95), A('thom-yorke', 'Thom Yorke', 0.93), A('portishead', 'Portishead', 0.7), A('bjork', 'Björk', 0.65), A('aphex-twin', 'Aphex Twin', 0.62), A('depeche-mode', 'Depeche Mode', 0.58), A('talking-heads', 'Talking Heads', 0.57), A('david-bowie', 'David Bowie', 0.56), A('muse', 'Muse', 0.55), A('lcd-soundsystem', 'LCD Soundsystem', 0.53), A('arcade-fire', 'Arcade Fire', 0.52)], albums: [{ id: 'alfaa', title: 'A Light for Attracting Attention', artistId: 'the-smile', artistName: 'The Smile', year: 2022, popularity: 82 }], tracks: [{ id: 'thin-thing', title: 'Thin Thing', artistId: 'the-smile', artistName: 'The Smile', popularity: 80 }] },
  'thom-yorke': { artist: { id: 'thom-yorke', name: 'Thom Yorke' }, similarArtists: [A('radiohead', 'Radiohead', 0.9), A('the-smile', 'The Smile', 0.93), A('aphex-twin', 'Aphex Twin', 0.7), A('massive-attack', 'Massive Attack', 0.69), A('bjork', 'Björk', 0.67), A('portishead', 'Portishead', 0.66), A('depeche-mode', 'Depeche Mode', 0.58), A('david-bowie', 'David Bowie', 0.56), A('talking-heads', 'Talking Heads', 0.54), A('lcd-soundsystem', 'LCD Soundsystem', 0.53)], albums: [{ id: 'anima', title: 'ANIMA', artistId: 'thom-yorke', artistName: 'Thom Yorke', year: 2019, popularity: 78 }], tracks: [{ id: 'twist', title: 'Twist', artistId: 'thom-yorke', artistName: 'Thom Yorke', popularity: 76 }] },
  muse: { artist: { id: 'muse', name: 'Muse' }, similarArtists: [A('radiohead', 'Radiohead', 0.83), A('depeche-mode', 'Depeche Mode', 0.63), A('the-cure', 'The Cure', 0.61), A('pink-floyd', 'Pink Floyd', 0.6), A('arcade-fire', 'Arcade Fire', 0.59), A('david-bowie', 'David Bowie', 0.57), A('massive-attack', 'Massive Attack', 0.5), A('talking-heads', 'Talking Heads', 0.49), A('lcd-soundsystem', 'LCD Soundsystem', 0.47), A('bjork', 'Björk', 0.46)], albums: [{ id: 'absolution', title: 'Absolution', artistId: 'muse', artistName: 'Muse', year: 2003, popularity: 84 }], tracks: [{ id: 'hysteria', title: 'Hysteria', artistId: 'muse', artistName: 'Muse', popularity: 88 }] },
  'massive-attack': { artist: { id: 'massive-attack', name: 'Massive Attack' }, similarArtists: [A('portishead', 'Portishead', 0.9), A('bjork', 'Björk', 0.78), A('radiohead', 'Radiohead', 0.79), A('thom-yorke', 'Thom Yorke', 0.69), A('aphex-twin', 'Aphex Twin', 0.66), A('depeche-mode', 'Depeche Mode', 0.58), A('the-cure', 'The Cure', 0.56), A('talking-heads', 'Talking Heads', 0.48), A('david-bowie', 'David Bowie', 0.47), A('lcd-soundsystem', 'LCD Soundsystem', 0.46)], albums: [{ id: 'mezzanine', title: 'Mezzanine', artistId: 'massive-attack', artistName: 'Massive Attack', year: 1998, popularity: 92 }], tracks: [{ id: 'teardrop', title: 'Teardrop', artistId: 'massive-attack', artistName: 'Massive Attack', popularity: 94 }] },
  portishead: { artist: { id: 'portishead', name: 'Portishead' }, similarArtists: [A('massive-attack', 'Massive Attack', 0.9), A('radiohead', 'Radiohead', 0.78), A('bjork', 'Björk', 0.75), A('aphex-twin', 'Aphex Twin', 0.66), A('thom-yorke', 'Thom Yorke', 0.66), A('depeche-mode', 'Depeche Mode', 0.55), A('the-cure', 'The Cure', 0.53), A('pink-floyd', 'Pink Floyd', 0.49), A('muse', 'Muse', 0.5), A('talking-heads', 'Talking Heads', 0.43)], albums: [{ id: 'dummy', title: 'Dummy', artistId: 'portishead', artistName: 'Portishead', year: 1994, popularity: 90 }], tracks: [{ id: 'glory-box', title: 'Glory Box', artistId: 'portishead', artistName: 'Portishead', popularity: 91 }] },
  bjork: { artist: { id: 'bjork', name: 'Björk' }, similarArtists: [A('aphex-twin', 'Aphex Twin', 0.8), A('massive-attack', 'Massive Attack', 0.78), A('radiohead', 'Radiohead', 0.77), A('portishead', 'Portishead', 0.75), A('thom-yorke', 'Thom Yorke', 0.67), A('depeche-mode', 'Depeche Mode', 0.6), A('david-bowie', 'David Bowie', 0.59), A('talking-heads', 'Talking Heads', 0.57), A('lcd-soundsystem', 'LCD Soundsystem', 0.5), A('arcade-fire', 'Arcade Fire', 0.49)], albums: [{ id: 'post', title: 'Post', artistId: 'bjork', artistName: 'Björk', year: 1995, popularity: 89 }], tracks: [{ id: 'hyperballad', title: 'Hyperballad', artistId: 'bjork', artistName: 'Björk', popularity: 87 }] }
};

export const mockPlayers: MockPlayer[] = [
  { id: 'living-room', name: 'Living Room', status: 'playing', currentTrack: 'Everything In Its Right Place', currentArtist: 'Radiohead' },
  { id: 'kitchen', name: 'Kitchen', status: 'paused', currentTrack: 'Teardrop', currentArtist: 'Massive Attack' },
  { id: 'office', name: 'Office', status: 'idle', currentTrack: 'N/A', currentArtist: 'Björk' }
];
